### ISSUE TITLE
cinfiguration

### ISSUE THREAD

**Issue by Ediher0504** [busel7/Arduino#1]
apakah ini bisa menggunakan android?

**Comment by busel7** [comment]
saat ini belum

**Comment by Ediher0504** [comment]
versi esp8266 kan ada wifi, ini bisa untuk setting kan?

**Comment by busel7** [comment]
ya bisa lewat wifi pakai browser, masih belum stabil, agak susah loading webnya, karena masih banyak pakai delay

**Comment by Ediher0504** [comment]
192.168.xx.x?
apa bagian x nya mas?

**Comment by busel7** [comment]
Script yang mana mas? defaultnya 192.168.4.1.

**Comment by Ediher0504** [comment]
sip, terus tingkatkan mas, semoga berkah dan menjadi amal ibadah, dan semoga di lancarkan rejeki nya, amin.

**Comment by busel7** [comment]
Sudah di update setting dengan wifi, silahkan gan dicoba, semoga bermanfaat.
