### ISSUE TITLE
Jws murotal versi 2.0

### ISSUE THREAD

**Issue by R364R365** [busel7/Arduino#4]
Saya kemaren beli 2 pcb jws murotal dan  saya coba pakai jws murotal versi 1 dengan file bin,  bisa masuk,  cuma loading awalnya lama baru menyala,  coneksi wiffi sering rewel, kalau di pasang dfminiplayer tidak bisa menyala

Kemudian pakai jws murotal yg versi 2.0 dan saya flash dengan file bin setekah selesai saya pasang pada rangkaian tidak respon pada p10 mati,  hanya lampu esp8266 lolin yg nyala

Saya coba pakai coding yg jwsmurotal 2.00 sesuai  petunjuk di Youtube semua saya donload dan pasang library,  pada saat complile saya pasang esp8266 tanpa perangkat tambahan eror di rtc3231 saya cek di library sudah ada,  nanti malam saya akan coba lagi dan saya foto erornya

**Comment by R364R365** [comment]
Saya coba barusan jws  murotal versi 3.0 dan 3.1 hasil bisa menyala cuman tulisan yg bagian atas sedikit bergetar,  sedangkan text info yg berjalan normal,  mp3 berfungi dengan baik,  cuma sedikit saran bang bonny,  kalau bisa untuk mp3 dibikin  forder 01 untuk tarhim sdh banar forder 02 play hari senin,  03 dengan isi firder 04 hari selasa dst,  terus tambah menu sebelum tahim mp3 yg di play apa berapa ment dan tarhim mp3  dipilih track dan beraoa menit
  
Tetrus satu hal lagii Font Arabnya di bikin lebih bagius yg natural biar yg lihat tidak kaku. , untuk coding saya masih belum berhasil,  trimakasih sukses mas bonny

**Comment by busel7** [comment]
Terkait flicker karena menggunakan library DMDESP untuk menstabilkan wifi, jika tidak ingin flicker bisa pakai HJS589 tapi wifi tidak stabil, saat ini baru ada dua pilihan tersebut :).
