### ISSUE TITLE
JWS Murotal Versi 2.00

### ISSUE THREAD

**Issue by R364R365** [busel7/Arduino#5]
Mas bonny kesalahan error di mana ya

C:\Users\compaq\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4\libraries\ESP8266WiFi\src\Arduino-master\bootloaders\eboot\eboot.c:15:19: fatal error: uzlib.h: No such file or directory
 #include <uzlib.h>
                   ^
compilation terminated.
exit status 1
Error compiling for board NodeMCU 1.0 (ESP-12E Module).

**Comment by busel7** [comment]
coba dicek lagi penginstalan arduino dan library pendukungnya, video Panduan Membuat JWS https://youtube.com/playlist?list=PLKuQ-UWqAt3O8WmFeoTbUa2keQKbdOXVv
