### ISSUE TITLE
jws murotal v2.00

### ISSUE THREAD

**Issue by R364R365** [busel7/Arduino#6]
bisa bantu mas apa yg salah ?

unable to create a folder to save the sketch: mkdir sketch: Access is denied.
Error compiling for board NodeMCU 1.0 (ESP-12E Module).

![image](https://user-images.githubusercontent.com/79157427/108371604-8036be00-7230-11eb-92e3-674409f61abd.png)

**Comment by busel7** [comment]
untuk permission / hak akses terkait penggunaan sistem operasi ya om, coba  di google aja.
