### ISSUE TITLE
hjs589_h error ,

### ISSUE THREAD

**Issue by Asep270316** [busel7/Arduino#7]
![image](https://user-images.githubusercontent.com/80524651/111016398-52ccd280-83e0-11eb-86f9-83fa1f4a34de.png)

assalammaualikum ,,mas bonny  klo error bgni bagaimana solusinya ,kesulitan mendapkan library nya mas ? mohon bantunannya ,,

wasalam .

**Comment by Asep270316** [comment]
![image](https://user-images.githubusercontent.com/80524651/111016708-f965a300-83e1-11eb-92c7-2fc513b5ece6.png)




tidak ada pilihan untuk di downloadnya mas bonny ..mohon bantuannya ,

**Comment by busel7** [comment]
ada dimenu yang titik titik ...  sebelah Add File, di klik aja nanti ada menu download, tampilan github sudah berubah semenjak video ini tayang https://youtu.be/SCGcVeJPvGQ
